#!/usr/bin/env python
import logging
from datetime import datetime

import click

from tcmlib import loader
from tcmlib import videoproc

logging.basicConfig(level=logging.DEBUG,
                    format="%(asctime)s %(levelname)s [%(module)s/%(funcName)s]: %(message)s")
LOG = logging.getLogger(__name__)


@click.command()
@click.option("-s", "--src", help="Path to video dir (either to SavedClips or SentryClips)", required=True)
@click.option("-d", "--dest", help="Destination path", required=True)
@click.option("-x", "--speed-ratio", help="Speed ratio; 1x is normal, 2x is twice as fast. Default is 2x.",
              default=2)
@click.option("-m", "--mins-back", default=2,
              help="Number of videos, or minutes to look back (if available). Recommended is a bit higher "
                   "than 1, because the last video might be really short. Default is 2.")
def main(src, dest, speed_ratio, mins_back):
    src, dest = loader.parse_paths(src, dest)

    start = datetime.now()
    paths = sorted((p for p in src.glob("*") if len(p.name) > 10))
    for path in sorted(paths):
        LOG.info(f"Next up: videos in {path}")
        vg = list(loader.select_latest_videos(path, last_n=mins_back))
        videoproc.merge_group(vg, dest, path.name, speed_ratio)

    end = datetime.now()
    LOG.info("Processing took {} sec".format((end-start).total_seconds()))


if __name__ == "__main__":
    main()
