#!/usr/bin/env python
import logging

import click

from tcmlib import loader
from tcmlib import videoproc

logging.basicConfig(level=logging.DEBUG)
LOG = logging.getLogger(__name__)


@click.command()
@click.option("-s", "--src", help="Path of mounted USB drive (contains the TeslaCam dir)", required=True)
@click.option("-d", "--dest", help="Destination path", required=True)
def main(src, dest):
    src, dest = loader.parse_paths(src, dest)
    loader.verify_paths(src, dest)

    for dir in sorted(src.glob("*")):
        LOG.info(f"Processing dir {dir}")
        vg = loader.select_latest_videos(dir)
        LOG.info(f"Will handle videos for {vg.timestamp_str}")
        videoproc.merge_group(vg, dest)
        # break


if __name__ == "__main__":
    main()
